### PR TITLE
Use Autoconf to build and package Radamsa

### PR DESCRIPTION
**Pull request by brarcher**
Related to the following closed issue:

  https://github.com/aoh/radamsa/issues/5

The following pull request will add support to Radamsa to build the necessary Makefiles using Autoconf. This will allow one to more easily find the necessary dependencies on multiple platforms and build. This should include GNU/Linux, UNIX, OSX, and Windows using MinGW and Cygwin.

With these changes, one should do the following to build:

```
$ autoreconf -i
$ ./configure
$ make
```

Unit tests are run with the following:

```
$ make check
```

Autoconf can also create a tarball for distribution. This tarball will include the radamsa.c file as well as the configure script and everything necessary to build. To create the tarball:

```
$ make dist
```

To build from the tarball:

```
$ tar xf radamsa-0.4.0.tar.gz 
$ cd radamsa-0.4.0
$ ./configure
$ make
```

There are a few features in the original Makefile which are not yet available. They are:
1) Does not download owl-lisp. Instead, the configure script checks if the ol binary is on the system. If it is missing, is instructs the user to install and compile it separately.
2) There is no target for running the benchmarks.

In addition, an AUTHORS file has been added which will list contributors to the project, including those outside of the project. If this merge request is accepted, the AUTHORS file contains information on my contribution. I would encourage the Radamsa team to update the file to include other contributors.

With these changes it should be easier to support multiple platforms and create a tarball for distribution.

Thank you for your consideration.

### CODE REVIEW

**Comment by brarcher** [comment]
For an example of how a release might look, see the example here:

https://github.com/brarcher/radamsa/releases/tag/0.4.1

One can build a tarball locally with

```
$ make dist
```

which will build the radamsa.c file and add it to the package. Then, the tarball can be uploaded to github.

FYI, to increment the version of Radamsa make the following change to configure.ac:

```
- AC_INIT([Radamsa], [0.4.0], [ouspg at ee.oulu.fi])
+ AC_INIT([Radamsa], [0.4.1], [ouspg at ee.oulu.fi])
```

**Comment by aoh** [comment]
Hi, 

Thanks for the pull request.

I'm not keen to pick it up though. Lack of support for autoconf is quite intentional. Your pull request is in a sense a good example of why this is so: even when done well, autoconf brings in extra dependencies, adds an extra step to builds and increases complexity, all while solving zero issues and making things more complicated compared to using just make.

Changing the build steps would also require people who have packaged radamsa and owl lisp for various platforms to change their build steps.

**Comment by brarcher** [comment]
Thanks for considering my pull request.

Before I go much further, I would like to say that I love Radamsa. The software has been really valuable in being able to fuzz arbitrary files and find vulnerabilities. Radamsa is a prime example of robust and simple to use software which can accomplish fuzzing as a part of regular software testing.

Please keep up the good work!

My intention with the autotools patches is to allow Radamsa to be easily compilable on multiple platforms. Certainly the hand crafted Makefile does work, however autotools adds some additional support and robustness to the table. For example:

1) Before generating the Makefile the configure script determines that the platform is sane to build on, the compiler is working, and all dependencies are available.
2) Enables cross-compiling support. For example, if one were interested in compiling Radamsa for an Arm device from and x86 device, one could do so with autotools. The existing Makefile shipped with Radamsa might have difficulty doing this.
3) Creating a tarball for distributing a Radamsa release and then testing it is relatively simple with autotools.

Radamsa does not need a build system such as autotools, however I believe that by using autotools Radamsa may be easier to build on many platforms, including cross compiling.

> autoconf brings in extra dependencies,

To be clear, it only brings extra dependencies (autotools itself) on the system which generates the configure script; any consumer of a generated tarball with the configure script would only need to have a shell interpreter available. Autotools is a fairly common component on GNU/Linux systems, as well as various UNIX and even MinGW and Cygwin systems.  The additional dependency should not be onerous.

I work with a project called Check (http://check.sourceforge.net/). Using autotools has allowed the project to support many more platforms than a hand maintained Makefile would allow.

> adds an extra step to builds and increases complexity

Although it does add one extra step (the configure script), the step can add robust checking on the host system and all necessary dependencies. The configure && make && make install steps for compiling and installing software is very common in the GNU/Linux world, and should also be familiar to many.

> all while solving zero issues and making things more complicated compared to using just make

As mentioned above, there are several issues that autotools solves, including checking for dependencies and the ability to build on the host system and cross compiling support. I will agree that it is more complex than simply using make, but the expectation is the additional support is provides is worth it.

> Changing the build steps would also require people who have packaged Radamsa and owl lisp for various platforms to change their build steps.

One could argue that by supporting autotools it would make including Radamsa into a package easier for package maintainers. Further, as the software is not yet 1.0 deciding to update the build process by using a standard, well known build system should be acceptable.

However, is there a possibility for a compromise? Could the hand crafted Makefile be included alongside the autotools support. Perhaps the existing Makefile could continue to be packaged, but if the configure script is invoked it would replace it for those who want to use autotools?

If the Radamsa project perhaps does not like autotools, would there be another build system which would be more amenable? Or, if Radamsa does need support to build owl-lisp (if it is not available) a configure script argument could be added which would optionally download the owl-lisp tarball and build it prior to building Radamsa.

Kindly consider utilizing a build system to generate a Makefile for Radamsa. If I have not provided a convincing argument, as least I tried. (:

**Comment by aoh** [comment]
Hi, 

It's stil not clear to me why there should be another separate step before compilation. I have limited time to work on my side projects, so it is essential to try to keep the complexity manageable. Adding complexity and features is easy. Keeping things simple is really hard. Autotools does decrease the overall complexity of configuring some projects to run in many kinds of environments. That just isn't a problem in this case. Radamsa builds with git clone + make + sudo make install on Linux, OpenBSD, FreeBSD, NetBSD, on Solaris last time I  checked, and has built with minimal hassle on Plan9 and Android. Oh, and Windows. It runs bit-exactly the same on all devices from 32-bit ARM Raspberry to 64-bit Xeon servers, and one can take the Radamsa sources, radamsa.fasl or radamsa.c file from any supported machine and run it in any supported environment without modifications. To crosscompile, one can use $ make CC=crosscompiler, or just compile the radamsa.c manually with a crosscompiler, which usually boils down to my-hardware-gcc -o radamsa radamsa.c. Owl Lisp was specifically designed to leave no external dependencies to the generated C-code to make the build process and shipping programs trivial.

There have been no complaints from packagers of radamsa, just a few extra make targets in case their build process has used some particular variables. So, from my point of view, the only remaining reason to bring in automake would be because everyone else is doing it. That has never worked well for me :)

**Pull request closed without merging**
